### ISSUE TITLE
Mejorar apariencia

### ISSUE THREAD

**Issue by DarwinGonzalez** [DarwinGonzalez/PracticaProyectoDSI#6]
Arreglar la apariencia mediante el style.css para que el panel aparezca en el centro de la pantalla, agregando un fondo que no sea blanco (posible imagen de la selva o algo por el estilo).

**Comment by alu0100825145** [comment]
Mejorado el posicionamiento del panel en el centro y cambiado el fondo de la página a color verde.

**Comment by alu0100824810** [comment]
Hice algunos cambios respecto al color del fondo, el aumento de tamaño del plano delimitado donde se mueve la serpiente y el color del título del juego.
